Модуль Кодов
Nexus-Technology-Group/Shortly pull request #2
Opened 2024-09-21 17:01 UTC by Wsuffy

2024-09-21 17:18 UTC, jassus213 requested changes

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/DTOs/CodeDTO.cs
> +    public Guid AuthorizationId { get; init; }
Зачем?

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/DTOs/CodeDTO.cs
> +    public string Value { get; init; }
```suggestion
    public string Value { get; init; } = string.Empty;
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/DTOs/CodeDTO.cs
> +    public string Email { get; init; }
```suggestion
    public string Email { get; init; } = string.Empty;
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeAlreadyExists.cs
> +public class CodeAlreadyExists : HttpRequestException
```suggestion
public class CodeAlreadyExistsException : HttpRequestException
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeAlreadyExists.cs
> +    public const string MESSAGE = "error.code.already.exists";
`type.assembly/module.payload`
```suggestion
    public const string MESSAGE = "error.code.alreadyExists";
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public const string MESSAGE = "error.code.is.not.valid";
`type.assembly/module.payload`
```suggestion
    public const string MESSAGE = "error.code.invalid";
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public CodeIsNotValidException(string messsage) : base(messsage, null, HttpStatusCode.Conflict)
Почему конфликт?

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeNotFoundException.cs
> +    public const string MESSAGE = "error.code.not.found";
```suggestion
    public const string MESSAGE = "error.code.notFound";
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Utils/CodeGenerator.cs
> +            currentCode += Random.Next(0, 9);
```suggestion
            currentCode += Random.Shared.Next(0, 9);
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Application/Utils/CodeGenerator.cs
> +    private static readonly Random Random = new Random();
Убрать

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Abstractions/ICodeManager.cs
> +    Task RemoveCodeAsync(RemoveCodeRequest request, CancellationToken cancellationToken);
Убрать слово код из методов, по менеджеру и так понятно, что бизнес операции проводятся над кодами

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Abstractions/ICodeProvider.cs
> +    Task IsCodeExistAndValidAsync(string email, string code, CodeType codeType, CancellationToken cancellationToken);
Убрать слово код

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Abstractions/Requests/RemoveCodeRequest.cs
> +public sealed record RemoveCodeRequest(string Email, string Value);
```suggestion
public sealed record ManagerRemoveCodeRequest(string Email, string Value);
```
Чтобы название запросов от слоя к слою различались

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Implementation/CodeProvider.cs
> +public class CodeProvider : ICodeProvider
Почему появилась отдельная имплементация под код провайдер, всегда делали `ICodeManager : ICodeProvider`

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Implementation/CodeProvider.cs
> +        var todayDate = DateTime.UtcNow;
Зачем эта переменная?

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Implementation/CodeManager.cs
> +        var expiredDate = DateTime.UtcNow.AddMinutes(CodesConstants.ConfirmationExpirationTime);
Я бы вынес длительность жизни кодов в appsettings.
И не `ConfirmationExpirationTime`, а `CodeConfirmationTTL`

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.BLL.Implementation/CodeManager.cs
> +        var expiredDate = DateTime.UtcNow.AddMinutes(CodesConstants.PasswordRecoveryExpirationTime);
Не `PasswordRecoveryExpirationTime`, а `CodePasswordRecoveryTTL`

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.DAL.Abstractions/CodesConstants.cs
> +    public static int PasswordRecoveryExpirationTime = 15;
Здесь уже не меняй, ибо переедет в appsettings, но зачем `static`, если `const`

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.DAL.Abstractions/CodesConstants.cs
> +﻿namespace Shortly.Codes.DAL.Abstractions;
Почему расположил в DAL?

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
Интересное решение, чтобы DAL знал, как создавать значение кода, но спорное. Вряд-ли это правило БД, скорее бизнес

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +        var code = await _codeCollection.Find(filter)
А где проверка на null и кастомное исключение, что кода не существует?

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +        var code = await _codeCollection.Find(filter).FirstOrDefaultAsync(cancellationToken);
перенести `FirstOrDefaultAsync` на след строку, как linq пишем

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Domain/Entities/Code.cs
> +    public string Email { get; init; }
```suggestion
    public string Value { get; init; } = string.Empty;
    
    public string Email { get; init; } = string.Empty;
```

2024-09-21 17:18 UTC, jassus213 commented on Shortly.Codes.Domain/Entities/Code.cs
> +public class Code
Не нашел BackgroundJob, который чистил бы протухшие коды

2024-09-21 17:27 UTC, Wsuffy commented on Shortly.Codes.Application/DTOs/CodeDTO.cs
> +    public Guid AuthorizationId { get; init; }
Исправил

2024-09-21 17:39 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
С моей точки зрения, чтобы не повторяться во всех типах кода (методах), сделал это на этом уровне, как будто на уровне БД это нормально, потому сущность Code, без значения кода не имеет смысл

2024-09-21 17:41 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
Это то понятно, должна ли DAL знать о имплементации создания кодов

2024-09-21 21:18 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
Насчёт этого, я бы задумался в том случае, если бы у нас был какой-то большой генератор, который используется в нескольких местах

А так мне кажется конкретно эта реализация будет использоваться только для кодов

2024-09-21 21:42 UTC, Wsuffy commented
Исправил коменты, добавил простенькую BackgroundJob, мы хотим через HangFire какой-нибудь?

2024-09-21 22:38 UTC, jassus213 commented
> Исправил коменты, добавил простенькую BackgroundJob, мы хотим через HangFire какой-нибудь?

Почитай и предложи решение, по распределенному планировщику

2024-09-22 17:58 UTC, Wsuffy commented
Используем либо HangFire, либо Quartz в охапке с Redis, запускаем либо по часам, каждые 12 часов, либо дейли

2024-09-22 18:44 UTC, jassus213 requested changes

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +    private readonly IMongoCollection<Code> _codeCollection;
Почему не через Storage, почему на прямую коллекцию тянем

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.Application/CodesConstants.cs
> +    #endregion
Написал же унести в appsettings и TTL у тебя в чем, в секундах, минутах, в бананах?

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeAlreadyExistsException.cs
> +public class CodeAlreadyExists : HttpRequestException
Еще раз напишу `CodeAlreadyExistsException`

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public const string MESSAGE = "error.invalid.code";
type.assembly/module.payload

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.BLL.Implementation/CodeManager.cs
> +        var expiredDate = DateTime.UtcNow.AddMinutes(CodesConstants.ConfirmationTTL);
Зачем эта переменная?

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.BLL.Implementation/CodeManager.cs
> +        var expiredDate = DateTime.UtcNow.AddMinutes(CodesConstants.PasswordRecoveryTTL);
Зачем эта переменная?

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
Оно всегда кажется, а потом может по ногам стрелять(

2024-09-22 18:44 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +        return code?.Map();
и зачем `?`, если сверху проверка на null

2024-09-23 16:39 UTC, Wsuffy commented on Shortly.Codes.Application/CodesConstants.cs
> +    #endregion
Нету app settings

2024-09-23 16:40 UTC, Wsuffy commented on Shortly.Codes.Application/Exceptions/CodeAlreadyExistsException.cs
> +public class CodeAlreadyExists : HttpRequestException
![Uploading image.png…]()

2024-09-23 16:43 UTC, Wsuffy commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public const string MESSAGE = "error.invalid.code";
что это значит

2024-09-23 16:43 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeAlreadyExistsException.cs
> +public class CodeAlreadyExists : HttpRequestException
Ну название файла изменено, а класса?

2024-09-23 16:45 UTC, jassus213 requested changes

2024-09-23 16:45 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
И жду предложения реализации, либо HostedService, либо Hangfire

2024-09-23 16:47 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
![image](https://github.com/user-attachments/assets/f3162566-dd8c-4a93-8d0b-4eb640d5c977)
Предложил

2024-09-23 16:48 UTC, Wsuffy commented on Shortly.Codes.Application/CodesConstants.cs
> +    #endregion
Нет AppSettings, чтобы создать я могу создать host, но в нем не будет регистрации других сервисов

2024-09-23 16:49 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public const string MESSAGE = "error.invalid.code";
error.code.invalid

2024-09-23 16:49 UTC, jassus213 commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public const string MESSAGE = "error.invalid.code";
тип сообщения.сборка в котором сообещние.полезная нагрузка об собщении

2024-09-23 16:50 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
Hangfire реализуй

2024-09-23 16:51 UTC, jassus213 commented on Shortly.Codes.Application/CodesConstants.cs
> +    #endregion
Ну тебе прям appsettings не обязательно, заведи нормальный класс настроек и где они нужны, принимай IOptions

2024-09-23 16:52 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
просто 3 раза было попрошено предложить, я предложил

2024-09-23 16:53 UTC, Wsuffy commented on Shortly.Codes.Application/Exceptions/CodeIsNotValidException.cs
> +    public const string MESSAGE = "error.invalid.code";
Поменял местами

2024-09-23 16:54 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
Ну во первых два раза, во-вторых надо писать в тредах, а не тупо комменты, по ним уведомления не приходят)

2024-09-23 16:54 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
но опять же таки, нет у нас хоста пока что, чтобы hangfire делать

2024-09-23 16:56 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
Буквально класс называется же CodeGenerator, который генерирует только коды, только длины 6, его больше никуда не заюзаешь кроме кода, решение какое, мне в бизнес логику это утащить?

2024-09-23 16:56 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
Заведи хост, если прям так сильно надо... Только по памяти, там у BG достаточно интерфейс реализовать и потом просто в хосте забиндить все

2024-09-23 16:58 UTC, jassus213 commented on Shortly.Codes.DAL.Mongo/CodeStorage.cs
> +            Value = CodeGenerator.Generate(),
Приходит бизнес и говорит, ребята, а сделайте на почте 8 символов и не только числа, а в смс 6 символов и только числа, предложи решение, возможной проблемы

2024-09-23 17:36 UTC, Wsuffy commented on Shortly.Codes.DAL.Mongo/BackgroundJobs/CodeCleanerJob.cs
> +public class CodeCleanerJob
Пигнанул. Сделал комит

2024-09-24 16:56 UTC, jassus213 approved these changes

2024-09-24 16:56 UTC, merged